version: '3.8'

services:

  park-track-db:
    platform: linux/x86_64
    command: [ "--max_connections=1000" ]
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: 'park-track'
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
    ports:
      - '5433:5432'
    expose:
      - '5433'
    volumes:
      - my-postgres-db:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: 'admin@admin.com'
      PGADMIN_DEFAULT_PASSWORD: 'admin'
    ports:
      - '80:80'
    depends_on:
      - park-track-db

volumes:
  my-db: { }
  my-postgres-db: { }
