services:
  park-track-db:
    platform: linux/x86_64
    command: [ "--max_connections=1000" ]
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: 'park-track'
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
    ports:
      - '5433:5432'
    expose:
      - '5432'
    volumes:
      - my-postgres-db:/var/lib/postgresql/data
    networks:
      - park−track-network

  pgadmin:
    depends_on:
      - park-track-db
    image: elestio/pgadmin:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: 'admin@admin.com'
      PGADMIN_DEFAULT_PASSWORD: 'admin'
      PGADMIN_LISTEN_PORT: 8080
    ports:
      - '80:8080'
    networks:
      - park−track-network

  backend:
    depends_on:
      - park-track-db
    image: esteban282/park-track-back:0.0.2
    restart: always
    ports:
      - '8080:8080'
    expose:
      - '8080'
    environment:
      - DB_URL=jdbc:postgresql://park-track-db:5432/park-track
      - APP_PATH=/
      - DB_USER=user
      - DB_PASS=password
    networks:
      - park−track-network

  frontend:
    depends_on:
      - backend
    image: esteban282/park-track-front:0.0.1
    restart: always
    ports:
      - '3000:3000'  # Mapea el puerto 3000 del contenedor al puerto 3000 de tu máquina host
    networks:
      - park−track-network

  analytics:
    depends_on:
      - backend
    image: esteban282/park-track-analytics:0.0.1
    restart: always
    ports:
      - '8000:8000'  # Mapea el puerto 8000 del contenedor al 8000 de tu máquina host
    networks:
      - park−track-network

volumes:
  my-postgres-db:

networks:
  park−track-network: